sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -e .[test]
script: python setup.py test
after_success:
- coverage xml
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
    secure: EmmooMDlYddJY1UlfN2kG0d6N0oeRrthKi4ABc3tDdUJYvAncUsI0ahKVEXmjslg1YdwG32SNCQhoRO3QjYPZ4IlwM+omB5ZZurOw94a6JRW67wyLNpM56wJoSMriVgcsR5y/bidUgGRe+MdwUNlRexvHcRiEVAck9gTkCCluB0=
